# Project information
site_name: RFS annotator
site_url: https://github.com/jacky-ct/rfs-annotator
site_author: Jackson Thomas
site_description: >-
  RFS internal tool for using AI to create bounding boxes for wind turbine damage diagnostics

# Repository
repo_name: 'jacky-ct/rfs-annotator'
repo_url: 'https://github.com/jacky-ct/rfs-annotator'
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2019 Piotr Skalski

# Page tree
nav:
  - Home: index.md
  - Import: import.md
  - Export: export.md
  - Shortcuts: shortcuts.md
  - Local setup: local-setup.md

# Configuration
theme:
  name: 'material'
  palette:
    primary: 'black'
    accent: 'indigo'
  font:
    text: Roboto
    code: Roboto Mono
  logo: 'img/logo.png'
  favicon: 'img/favicon.png'
  features:
    - navigation.expand
  icon:
    repo: fontawesome/brands/github
    
# Google Analytics
google_analytics:
  - 'UA-155837750-2'
  - 'auto'

# Extensions
markdown_extensions:
  - attr_list
  - def_list
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
